# Generated by Django 3.2.4 on 2021-07-16 13:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("issue_tracker", "0002_alter_issue_project"),
    ]

    operations = [
        migrations.AlterField(
            model_name="issue",
            name="update_date",
            field=models.DateTimeField(null=True),
        ),
    ]
