# Generated by Django 3.2.4 on 2021-07-16 13:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("issue_tracker", "0004_alter_issue_update_date"),
    ]

    operations = [
        migrations.AddField(
            model_name="issue",
            name="title",
            field=models.CharField(default="", max_length=50),
        ),
    ]
