# Generated by Django 3.2.4 on 2021-07-16 13:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("issue_tracker", "0005_issue_title"),
    ]

    operations = [
        migrations.AlterField(
            model_name="issue",
            name="title",
            field=models.CharField(max_length=50),
        ),
    ]
