# Generated by Django 3.2.4 on 2021-07-17 14:08

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("issue_tracker", "0011_auto_20210717_1458"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="project",
            name="member",
        ),
        migrations.AddField(
            model_name="project",
            name="member",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
