# Generated by Django 3.2.4 on 2021-08-11 11:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("issue_tracker", "0014_alter_issue_creator"),
    ]

    operations = [
        migrations.AlterField(
            model_name="issue",
            name="description",
            field=models.CharField(max_length=100, null=True),
        ),
    ]
