# Generated by Django 3.2.4 on 2021-08-11 18:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("issue_tracker", "0015_alter_issue_description"),
    ]

    operations = [
        migrations.AlterField(
            model_name="issue",
            name="description",
            field=models.CharField(max_length=250, null=True),
        ),
    ]
