# Generated by Django 3.2.4 on 2021-08-14 12:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('issue_tracker', '0018_auto_20210812_1909'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='issue',
            name='tags',
        ),
        migrations.DeleteModel(
            name='IssueTag',
        ),
    ]
