# Generated by Django 3.2.4 on 2021-08-14 14:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('issue_tracker', '0019_auto_20210814_1452'),
    ]

    operations = [
        migrations.AlterField(
            model_name='issue',
            name='update_date',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
