# Generated by Django 3.2.4 on 2021-08-16 19:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('issue_tracker', '0024_developerapplication_leaderapplication'),
    ]

    operations = [
        migrations.RenameField(
            model_name='project',
            old_name='member',
            new_name='developer',
        ),
    ]
