# Generated by Django 3.2.4 on 2021-08-22 11:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('issue_tracker', '0028_alter_project_description'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='historicalissue',
            name='comment',
        ),
        migrations.RemoveField(
            model_name='issue',
            name='comment',
        ),
        migrations.AddField(
            model_name='issue',
            name='comment',
            field=models.ManyToManyField(blank=True, null=True, to='issue_tracker.Comment'),
        ),
    ]
