# Generated by Django 3.2.4 on 2021-08-22 11:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('issue_tracker', '0030_alter_issue_comment'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='issue',
            name='comment',
        ),
        migrations.AddField(
            model_name='comment',
            name='issue',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='issue_tracker.issue'),
        ),
    ]
