# Generated by Django 3.2.4 on 2021-08-22 11:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('issue_tracker', '0032_alter_comment_issue'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='text',
            field=models.CharField(max_length=250),
        ),
        migrations.AlterField(
            model_name='project',
            name='name',
            field=models.CharField(default='None', max_length=25),
        ),
    ]
